# *********************************
# * Parameters for metqc pipeline *
# *********************************

# List of files
list_files: "/home/aschick/projects/arrieta/list_files_test.txt"
# Path to raw sequences
path: "/home/aschick/projects/arrieta/data/rawdata/"
# Suffix for forward reads
for: "_R1_001"
# Suffix for reverse reads
rev: "_R2_001"
# Run fastqc and multiqc only
qc_only: FALSE

### Cutadapt parameters
# Choose whether to run cutadapt
run_cutadapt: FALSE
# Adapters for cutadapt
fwd_adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
rev_adapter: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
# Minimum length for cutadapt
minlength: 60
# Maximum number of N bases allowed
maxn: 10

### Prinseq parameters
trimleft: 20
trimright: 20
trim_qual_window: 10
trim_qual_step : 2
trim_qual_type: "mean"
trim_qual_rule: "gt"
lc_method: "dust"
lc_threshold: 7

### BMtagger Parameters
# Choose whether to run bmtagger
run_bmtagger: TRUE
# Index for bmfilter (part of bmtagger), bitmask file
bmfilter_ref: "/home/aschick/refs/hg19/hg19_rRNA_mito_Hsapiens_rna_reference.bitmask"
# Index for srprism (part of bmtagger)
srprism_ref: "/home/aschick/refs/hg19/hg19_rRNA_mito_Hsapiens_rna_reference.srprism"

### BBMap parameters
# Choose whether to run bbmap
run_bbmap: FALSE
# Path and name of reference fasta for bbmap
bbmap_ref: "/home/aschick/refs/hs37.fa"
