# List of files
list_files: "ref_files/list_files.txt"

# Path to raw sequences
path: data/rawdata/

# Number of threads
num_threads: 28

# Adapters
fwd_adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
rev_adapter: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT

# Any other parameters
