# **********************************
# * Parameters for metqc pipeline *
# **********************************

# List of files
list_files: "ref_files/list_files.txt"

# Path to raw sequences
path: "data/rawdata/"

# Path to human genome reference files for bmtagger
path_hg: "ref_files/hg19/"

# Path and name of reference fasta for bbmap_env
bbmap_ref: "ref_files/hs37/hs37.fa"

# Number of threads
num_threads: 28

# Adapters
fwd_adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
rev_adapter: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT

# Any other parameters
