# **********************************
# * Parameters for metqc pipeline *
# **********************************

# List of files
list_files: "/home/aschick/projects/hmptest/list_files.txt"

# Path to raw sequences
path: "/home/aschick/projects/hmptest/data/rawdata/"

# Path and name of reference fasta for bbmap
bbmap_ref: "/home/aschick/projects/test_metqc/ref_files/hs37/hs37.fa"

# Number of threads
num_threads: 28

# Adapters
fwd_adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
rev_adapter: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT

# Any other parameters
